#!/usr/bin/env python3
"""Die neuen Texte des Weissware-Plugins.

Wird von ww_texte_einbauen.py in ww_sprache_erzeugen.py eingesetzt. Getrennt
gehalten, damit die Texte an einer Stelle lesbar beieinanderstehen.
"""

DE = {
# ---- Allgemein ----
"ALLG.GERAET": "Gerät",
"ALLG.GERAETE": "Geräte",
"ALLG.IN_BETRIEB": "in Betrieb",
"ALLG.ZUSTAND": "Zustand",
"ALLG.RESTZEIT": "Restzeit",
"ALLG.KEIN_FERNSTART": "keine Fernstart-Freigabe",

# ---- Einstellungen: Anbieter ----
"EINST.H_ANBIETER": "Anbieter",
"EINST.ANBIETER_ERKLAERUNG": "Drei &Ouml;kosysteme, ein gemeinsames Modell. Eingeschaltet wird nur, was Sie wirklich haben &mdash; jeder eingeschaltete Anbieter kostet Anfragen, auch wenn kein Ger&auml;t da ist. Bei Home Connect und Miele brauchen Sie ein <b>kostenloses Entwicklerkonto</b>, weil beide nur registrierten Anwendungen antworten; SmartThings kommt mit einem Token aus.",
"EINST.L_HC_EIN": "Home Connect abfragen",
"EINST.L_HC_ID": "Client-ID",
"EINST.H_HC_ID": "Aus dem Entwicklerportal von Home Connect, Abschnitt <i>Applications</i>. Legen Sie dort eine Anwendung mit dem Anmeldeverfahren <b>Device Flow</b> an &mdash; das ist das einzige, das ohne Bildschirm am Ger&auml;t auskommt.",
"EINST.L_HC_SECRET": "Client Secret",
"EINST.H_HC_SECRET": "Nur f&uuml;r das Erneuern des Zugriffstokens n&ouml;tig. Bleibt das Feld leer, bleibt das gespeicherte Geheimnis unver&auml;ndert.",
"EINST.L_HC_SIMULATOR": "Simulator statt echter Geräte verwenden",
"EINST.H_HC_SIMULATOR": "Home Connect stellt simulierte Ger&auml;te bereit. Damit l&auml;sst sich alles einrichten und in Loxone nachbauen, bevor eine echte Maschine angeschlossen ist. <b>Achtung:</b> Simulator und echte Ger&auml;te brauchen verschiedene Client-IDs.",
"EINST.L_MIELE_EIN": "Miele abfragen",
"EINST.L_MIELE_ID": "Client-ID",
"EINST.H_MIELE_ID": "Aus dem Miele-Entwicklerportal, Abschnitt <i>Get involved</i>. Als Weiterleitungsadresse tragen Sie dort <span class='sm-mono'>http://localhost</span> ein &mdash; die Adresse muss nicht erreichbar sein, der Code wird von Hand zur&uuml;ckkopiert.",
"EINST.L_MIELE_SECRET": "Client Secret",
"EINST.L_ST_EIN": "SmartThings abfragen",
"EINST.L_ST_TOKEN": "Personal Access Token",
"EINST.H_ST_TOKEN": "Aus dem SmartThings-Entwicklerportal. Bleibt das Feld leer, bleibt das gespeicherte Token unver&auml;ndert.",
"EINST.ST_WARNUNG": "<b>Vorbehalt.</b> Samsung hat die Lebensdauer neu ausgestellter Personal Access Tokens am 30.12.2024 auf <b>24 Stunden</b> verk&uuml;rzt und die Ratengrenzen gesenkt. F&uuml;r Dauerbetrieb verlangt Samsung eine registrierte Anwendung mit einem von au&szlig;en erreichbaren Webhook &mdash; das kann ein LoxBerry hinter einem Router nicht ohne Weiteres. Praktisch hei&szlig;t das: <b>Sie m&uuml;ssen das Token t&auml;glich erneuern.</b> Wer damit nicht leben will, l&auml;sst SmartThings aus. Wer ein &auml;lteres Token von vor dem 30.12.2024 hat, ist nicht betroffen.",
"EINST.GESETZT": "gespeichert (%d Zeichen) – leer lassen, um es zu behalten",
"EINST.LEER": "noch nichts gespeichert",
"EINST.WARN_HC_OHNE_ID": "Home Connect ist eingeschaltet, aber es ist keine Client-ID hinterlegt. So schlägt jeder Abruf fehl.",
"EINST.WARN_MIELE_OHNE_ID": "Miele ist eingeschaltet, aber es ist keine Client-ID hinterlegt. So schlägt jeder Abruf fehl.",
"EINST.WARN_ST_OHNE_TOKEN": "SmartThings ist eingeschaltet, aber es ist kein Token hinterlegt. So schlägt jeder Abruf fehl.",

# ---- Einstellungen: Anmeldung ----
"EINST.H_ANMELDUNG": "Anmeldung",
"EINST.ANMELDUNG_ERKLAERUNG": "Erst speichern, dann anmelden. Die Anmeldung legt einen Erneuerungsschl&uuml;ssel ab, mit dem sich der Dienst von selbst weiter anmeldet &mdash; Sie m&uuml;ssen das also nur einmal tun. Ausnahme ist SmartThings, siehe oben.",
"EINST.ANGEMELDET": "angemeldet",
"EINST.HC_SCHRITT1": "Auf <i>Anmeldung beginnen</i> dr&uuml;cken. Danach erscheinen hier ein Code und eine Adresse; die Adresse in einem beliebigen Browser &ouml;ffnen, den Code eingeben und den Zugriff erlauben. Zum Schluss auf <i>Anmeldung abschlie&szlig;en</i> dr&uuml;cken.",
"EINST.HC_SCHRITT2": "Die Anmeldung l&auml;uft. &Ouml;ffnen Sie die Adresse in einem Browser, geben Sie den Code ein, erlauben Sie den Zugriff &mdash; und dr&uuml;cken Sie dann hier auf <i>Anmeldung abschlie&szlig;en</i>.",
"EINST.HC_CODE": "Code",
"EINST.HC_ADRESSE": "Adresse",
"EINST.HC_GUELTIG": "gültig noch",
"EINST.K_HC_START": "Anmeldung beginnen",
"EINST.K_HC_FERTIG": "Anmeldung abschließen",
"EINST.HC_BEGONNEN": "Die Anmeldung wurde begonnen. Code und Adresse stehen unten — Sie haben fünf Minuten.",
"EINST.HC_FERTIG": "Home Connect ist angemeldet.",
"EINST.HC_NOCH_NICHT": "Noch nicht bestätigt. Code im Browser eingeben, Zugriff erlauben und dann erneut auf „Anmeldung abschließen“ drücken.",
"EINST.MIELE_SCHRITTE": "Miele bietet <b>kein</b> Verfahren f&uuml;r Ger&auml;te ohne Bildschirm an. Deshalb von Hand: die Adresse unten in einen Browser kopieren, mit dem Miele-Konto anmelden, die Ger&auml;te ausw&auml;hlen, die freigegeben werden sollen. Danach landen Sie auf einer Seite, die nicht l&auml;dt &mdash; das ist richtig so. Aus deren <b>Adresszeile</b> den Teil hinter <span class='sm-mono'>code=</span> kopieren (oder die ganze Adresse) und hier einf&uuml;gen.",
"EINST.MIELE_OHNE_ID": "Erst die Client-ID oben eintragen und speichern — ohne sie lässt sich keine Anmeldeadresse bilden.",
"EINST.L_MIELE_CODE": "Code aus der Adresszeile",
"EINST.H_MIELE_CODE": "Die ganze Adresse geht auch &mdash; der Code wird daraus herausgesucht. Der Code ist nur wenige Minuten g&uuml;ltig und l&auml;sst sich genau einmal einl&ouml;sen.",
"EINST.K_MIELE_CODE": "Code einlösen",
"EINST.MIELE_FERTIG": "Miele ist angemeldet.",
"EINST.FEHLER_MIELE_CODE": "Der eingegebene Wert sieht nicht wie ein Anmeldecode aus. Er wurde nicht eingelöst.",
"EINST.ST_SCHRITTE": "SmartThings braucht keine Anmeldung &mdash; das Token oben gen&uuml;gt. Es l&auml;uft allerdings nach 24 Stunden ab; dann tragen Sie hier ein neues ein und speichern.",

# ---- Einstellungen: Takt ----
"EINST.TAKT_ERKLAERUNG": "<b>Der eigentliche Grund f&uuml;r dieses Plugin.</b> Ein starrer Abfragezyklus ist entweder zu langsam f&uuml;r eine brauchbare Restzeit oder zu schnell f&uuml;r die Ratengrenzen des Anbieters. Hier gibt es zwei Takte: einen weiten, solange nichts l&auml;uft, und einen engen, sobald mindestens ein Ger&auml;t arbeitet. Umgeschaltet wird von selbst.",
"EINST.L_TAKT_RUHE": "Takt in Ruhe (Sekunden)",
"EINST.H_TAKT_RUHE": "Abstand, solange kein Ger&auml;t l&auml;uft. F&uuml;nf Minuten sind reichlich &mdash; eine Waschmaschine, die aus ist, wird nicht in einer Minute fertig.",
"EINST.L_TAKT_BETRIEB": "Takt im Betrieb (Sekunden)",
"EINST.H_TAKT_BETRIEB": "Abstand, sobald mindestens ein Ger&auml;t arbeitet. Untergrenze 60 Sekunden: Home Connect nennt h&auml;ufiges Abfragen in seinen Best Practices ausdr&uuml;cklich als h&auml;ufigste Ursache f&uuml;r HTTP 429.",
"EINST.FEHLER_TAKT_TAUSCH": "Der Takt in Ruhe ist kleiner als der im Betrieb. Das ist verkehrt herum — bitte die beiden Werte tauschen.",
"EINST.L_SPRACHE": "Sprache der Anbieterantworten",
"EINST.H_SPRACHE": "In dieser Sprache liefern die Anbieter die Programmnamen und Zustandstexte. Auf die Sprache dieser Oberfl&auml;che hat das keinen Einfluss.",
"EINST.FEHLER_SPRACHE": "Die Sprache muss die Form de-DE haben.",

# ---- Einstellungen: Tabelle ----
"EINST.KEINE_GERAETE": "Noch kein Ger&auml;t erkannt. Bis zum ersten erfolgreichen Abruf ist das normal: Anbieter einschalten, Zugangsdaten eintragen, speichern, anmelden, Dienst starten und eine Taktl&auml;nge abwarten. Bleibt die Liste danach leer, steht der Grund im Reiter <i>Test</i> und in der Logdatei.",
"EINST.T_ANBIETER": "Anbieter",
"EINST.T_NAME": "Name",
"EINST.T_TYP": "Art",
"EINST.T_MARKE": "Marke",
"EINST.T_ZUSTAND": "Zustand",
"EINST.T_FERNSTART": "Fernstart",
"EINST.T_KENNUNG": "Kennung",
"EINST.KENNUNG_HINWEIS": "In allen Adressen kann statt der Nummer auch die Kennung stehen &mdash; <span class='sm-mono'>geraet=SIEMENS-HCS03WCH1-…</span>. Das ist stabiler, wenn sp&auml;ter ein Ger&auml;t dazukommt und sich die Reihenfolge verschiebt.",

# ---- Loxone ----
"LOX.MEHRERE_GERAETE": "Mehrere Geräte — je Gerät ein eigener virtueller Eingang:",
"LOX.S4_LEER": "<b>Nicht jeder Anbieter liefert jeden Wert.</b> Home Connect meldet weder Energie- noch Wasserverbrauch; SmartThings meldet keinen Fortschritt in Prozent; Miele liefert beides, aber nur bei Ger&auml;ten mit EcoFeedback. Was fehlt, ist ein Strich &mdash; keine 0.",
"LOX.T_VA_START": "Programm starten (das am Gerät gewählte)",
"LOX.T_VA_START_PROG": "Bestimmtes Programm starten",
"LOX.T_VA_STOP": "Programm abbrechen",
"LOX.T_VA_PAUSE": "Programm anhalten",
"LOX.T_VA_FORTSETZEN": "Programm fortsetzen",
"LOX.T_VA_EIN": "Gerät einschalten",
"LOX.T_VA_AUS": "Gerät ausschalten",

# ---- Test ----
"TEST.F_ANBIETER": "Ist mindestens ein Anbieter eingeschaltet?",
"TEST.A_ANBIETER": "ja, %d",
"TEST.A_KEIN_ANBIETER": "nein — Reiter Einstellungen",
"TEST.F_ZUGANG": "%s: sind Zugangsdaten hinterlegt?",
"TEST.A_ZUGANG_DA": "ja",
"TEST.A_ZUGANG_FEHLT": "nein",
"TEST.F_ANGEMELDET": "%s: ist die Anmeldung abgeschlossen?",
"TEST.A_ANGEMELDET": "ja, der Dienst erneuert sich selbst",
"TEST.A_NICHT_ANGEMELDET": "nein — Reiter Einstellungen, Abschnitt Anmeldung",
"TEST.A_ST_TOKEN": "entfällt — SmartThings braucht nur das Token (24 Stunden gültig)",
"TEST.F_GERAETE": "Sind Geräte erkannt?",
"TEST.A_GERAETE": "ja, %d",
"TEST.A_KEINE_GERAETE": "nein — bis zum ersten erfolgreichen Abruf normal",
"TEST.F_AUSFALL": "Hat %s geantwortet?",
"TEST.L_GERAET": "Gerät (laufende Nummer)",
"TEST.L_PROGRAMM": "Programm (freiwillig)",
"TEST.H_PROGRAMM": "Leer lassen, um das am Ger&auml;t gew&auml;hlte Programm zu starten &mdash; das ist der Regelfall. Ein Programmschl&uuml;ssel sieht bei Home Connect aus wie <span class='sm-mono'>LaundryCare.Washer.Program.Cotton</span>; welche es gibt, zeigt der Knopf <i>Rohdaten als JSON ansehen</i>.",
"TEST.M_GERAET_UNGUELTIG": "Die Gerätenummer ist keine Zahl zwischen 1 und 999.",
"TEST.M_PROGRAMM_UNGUELTIG": "Der Programmschlüssel enthält Zeichen, die dort nicht vorkommen. Er wurde nicht gesendet.",
"TEST.K_STATUS": "Status abrufen",
"TEST.K_VERBRAUCH": "Verbrauch abrufen",
"TEST.K_GERAETE": "Geräte auflisten",
"TEST.K_START": "Programm starten",
"TEST.K_STOP": "Programm abbrechen",
"TEST.K_PAUSE": "Anhalten",
"TEST.K_FORTSETZEN": "Fortsetzen",
"TEST.K_EIN": "Gerät ein",
"TEST.K_AUS": "Gerät aus",

# ---- Statusfelder ----
"WW_FELD.ZUSTAND": "0 aus, 1 bereit, 2 läuft, 3 pausiert, 4 fertig, 5 Störung",
"WW_FELD.LAEUFT": "1 = ein Programm läuft gerade",
"WW_FELD.FERTIG": "1 = Programm beendet, noch nicht quittiert",
"WW_FELD.VERBUNDEN": "1 = das Gerät ist für den Anbieter erreichbar",
"WW_FELD.TUER": "1 = Tür offen",
"WW_FELD.FORTSCHR": "Fortschritt des laufenden Programms",
"WW_FELD.RESTMIN": "Restzeit bis zum Programmende",
"WW_FELD.STARTMIN": "Zeit bis zum Start bei Startvorwahl",
"WW_FELD.LAUFMIN": "Bisherige Laufzeit des Programms",
"WW_FELD.FERNSTART": "1 = am Gerät ist der Fernstart freigegeben",
"WW_FELD.FERNBED": "1 = Fernbedienung ist erlaubt",
"WW_FELD.NETZ": "1 = Gerät eingeschaltet",

# ---- Verbrauchsfelder ----
"WW_VFELD.ENERGIE": "Energieverbrauch des laufenden Programms",
"WW_VFELD.WASSER": "Wasserverbrauch des laufenden Programms",
"WW_VFELD.TEMP": "Eingestellte Temperatur",
"WW_VFELD.SCHLEUDER": "Eingestellte Schleuderdrehzahl",

# ---- MQTT ----
"WW_MQTT.GERAETE": "Anzahl der erkannten Geräte",
"WW_MQTT.NAME": "Name des Geräts",
"WW_MQTT.ANBIETER": "homeconnect, miele oder smartthings",
"WW_MQTT.ZUSTAND": "0 aus, 1 bereit, 2 läuft, 3 pausiert, 4 fertig, 5 Störung",
"WW_MQTT.ZUSTAND_TEXT": "Zustand im Klartext, wie der Anbieter ihn nennt",
"WW_MQTT.LAEUFT": "1 = ein Programm läuft gerade",
"WW_MQTT.FERTIG": "1 = Programm beendet",
"WW_MQTT.VERBUNDEN": "1 = für den Anbieter erreichbar",
"WW_MQTT.TUER": "1 = Tür offen",
"WW_MQTT.FORTSCHRITT": "Fortschritt in Prozent",
"WW_MQTT.RESTZEIT": "Restzeit in Minuten",
"WW_MQTT.STARTZEIT": "Zeit bis zum Start in Minuten",
"WW_MQTT.LAUFZEIT": "Bisherige Laufzeit in Minuten",
"WW_MQTT.FERNSTART": "1 = Fernstart am Gerät freigegeben",
"WW_MQTT.FERNBED": "1 = Fernbedienung erlaubt",
"WW_MQTT.NETZ": "1 = Gerät eingeschaltet",
"WW_MQTT.ENERGIE": "Energieverbrauch in kWh",
"WW_MQTT.WASSER": "Wasserverbrauch in Litern",
"WW_MQTT.TEMPERATUR": "Eingestellte Temperatur in Grad Celsius",
"WW_MQTT.SCHLEUDER": "Eingestellte Schleuderdrehzahl",
"WW_MQTT.PROGRAMM": "Laufendes Programm im Klartext",
}

EN = {
"ALLG.GERAET": "Appliance",
"ALLG.GERAETE": "Appliances",
"ALLG.IN_BETRIEB": "running",
"ALLG.ZUSTAND": "State",
"ALLG.RESTZEIT": "Time left",
"ALLG.KEIN_FERNSTART": "no remote start release",

"EINST.H_ANBIETER": "Providers",
"EINST.ANBIETER_ERKLAERUNG": "Three ecosystems, one common model. Only switch on what you actually own &mdash; every enabled provider costs requests even if it has no appliances. Home Connect and Miele need a <b>free developer account</b> because both only answer registered applications; SmartThings gets by with a token.",
"EINST.L_HC_EIN": "Poll Home Connect",
"EINST.L_HC_ID": "Client ID",
"EINST.H_HC_ID": "From the Home Connect developer portal, section <i>Applications</i>. Create an application using the <b>Device Flow</b> &mdash; the only method that works without a screen on the device.",
"EINST.L_HC_SECRET": "Client secret",
"EINST.H_HC_SECRET": "Only needed to refresh the access token. Leaving the field empty keeps the stored secret.",
"EINST.L_HC_SIMULATOR": "Use the simulator instead of real appliances",
"EINST.H_HC_SIMULATOR": "Home Connect provides simulated appliances. That lets you set everything up and rebuild it in Loxone before a real machine is connected. <b>Note:</b> the simulator and real appliances need different client IDs.",
"EINST.L_MIELE_EIN": "Poll Miele",
"EINST.L_MIELE_ID": "Client ID",
"EINST.H_MIELE_ID": "From the Miele developer portal, section <i>Get involved</i>. Enter <span class='sm-mono'>http://localhost</span> as the redirect address &mdash; it does not have to be reachable, the code is copied back by hand.",
"EINST.L_MIELE_SECRET": "Client secret",
"EINST.L_ST_EIN": "Poll SmartThings",
"EINST.L_ST_TOKEN": "Personal access token",
"EINST.H_ST_TOKEN": "From the SmartThings developer portal. Leaving the field empty keeps the stored token.",
"EINST.ST_WARNUNG": "<b>Reservation.</b> On 30 December 2024 Samsung cut the lifetime of newly issued personal access tokens to <b>24 hours</b> and lowered the rate limits. For continuous operation Samsung requires a registered application with a publicly reachable webhook &mdash; which a LoxBerry behind a router cannot easily provide. In practice: <b>you have to renew the token every day.</b> If you do not want to live with that, leave SmartThings switched off. Tokens issued before 30 December 2024 are not affected.",
"EINST.GESETZT": "stored (%d characters) – leave empty to keep it",
"EINST.LEER": "nothing stored yet",
"EINST.WARN_HC_OHNE_ID": "Home Connect is enabled but no client ID is stored. Every poll will fail.",
"EINST.WARN_MIELE_OHNE_ID": "Miele is enabled but no client ID is stored. Every poll will fail.",
"EINST.WARN_ST_OHNE_TOKEN": "SmartThings is enabled but no token is stored. Every poll will fail.",

"EINST.H_ANMELDUNG": "Sign-in",
"EINST.ANMELDUNG_ERKLAERUNG": "Save first, then sign in. Signing in stores a refresh key the service uses to keep itself signed in &mdash; so you only have to do this once. SmartThings is the exception, see above.",
"EINST.ANGEMELDET": "signed in",
"EINST.HC_SCHRITT1": "Press <i>Begin sign-in</i>. A code and an address will appear here; open the address in any browser, enter the code and grant access. Finally press <i>Complete sign-in</i>.",
"EINST.HC_SCHRITT2": "Sign-in is in progress. Open the address in a browser, enter the code, grant access &mdash; then press <i>Complete sign-in</i> here.",
"EINST.HC_CODE": "Code",
"EINST.HC_ADRESSE": "Address",
"EINST.HC_GUELTIG": "valid for another",
"EINST.K_HC_START": "Begin sign-in",
"EINST.K_HC_FERTIG": "Complete sign-in",
"EINST.HC_BEGONNEN": "Sign-in has begun. The code and address are below — you have five minutes.",
"EINST.HC_FERTIG": "Home Connect is signed in.",
"EINST.HC_NOCH_NICHT": "Not confirmed yet. Enter the code in the browser, grant access and then press 'Complete sign-in' again.",
"EINST.MIELE_SCHRITTE": "Miele offers <b>no</b> flow for devices without a screen. So by hand: copy the address below into a browser, sign in with your Miele account and pick the appliances to release. You will then land on a page that does not load &mdash; that is expected. Copy the part after <span class='sm-mono'>code=</span> from its <b>address bar</b> (or the whole address) and paste it here.",
"EINST.MIELE_OHNE_ID": "Enter and save the client ID above first — without it no sign-in address can be built.",
"EINST.L_MIELE_CODE": "Code from the address bar",
"EINST.H_MIELE_CODE": "The whole address works too &mdash; the code is extracted from it. The code is valid for a few minutes and can be redeemed exactly once.",
"EINST.K_MIELE_CODE": "Redeem code",
"EINST.MIELE_FERTIG": "Miele is signed in.",
"EINST.FEHLER_MIELE_CODE": "The value entered does not look like a sign-in code. It was not redeemed.",
"EINST.ST_SCHRITTE": "SmartThings needs no sign-in &mdash; the token above is enough. It does expire after 24 hours; enter a new one here and save.",

"EINST.TAKT_ERKLAERUNG": "<b>The actual reason for this plugin.</b> A fixed polling cycle is either too slow for a useful remaining time or too fast for the provider's rate limits. Here there are two intervals: a wide one while nothing is running and a tight one as soon as at least one appliance is working. Switching happens automatically.",
"EINST.L_TAKT_RUHE": "Interval when idle (seconds)",
"EINST.H_TAKT_RUHE": "Interval while no appliance is running. Five minutes is plenty &mdash; a washing machine that is off will not finish within a minute.",
"EINST.L_TAKT_BETRIEB": "Interval when running (seconds)",
"EINST.H_TAKT_BETRIEB": "Interval as soon as at least one appliance is working. Lower limit 60 seconds: Home Connect explicitly names frequent polling in its best practices as the most common cause of HTTP 429.",
"EINST.FEHLER_TAKT_TAUSCH": "The idle interval is smaller than the running one. That is the wrong way round — please swap the two values.",
"EINST.L_SPRACHE": "Language of the provider responses",
"EINST.H_SPRACHE": "The providers return programme names and state texts in this language. It has no effect on the language of this user interface.",
"EINST.FEHLER_SPRACHE": "The language must have the form de-DE.",

"EINST.KEINE_GERAETE": "No appliance detected yet. That is normal until the first successful poll: enable a provider, enter the credentials, save, sign in, start the service and wait one interval. If the list is still empty afterwards, the reason is in the <i>Test</i> tab and in the log file.",
"EINST.T_ANBIETER": "Provider",
"EINST.T_NAME": "Name",
"EINST.T_TYP": "Type",
"EINST.T_MARKE": "Brand",
"EINST.T_ZUSTAND": "State",
"EINST.T_FERNSTART": "Remote start",
"EINST.T_KENNUNG": "Identifier",
"EINST.KENNUNG_HINWEIS": "Every address also accepts the identifier instead of the number &mdash; <span class='sm-mono'>geraet=SIEMENS-HCS03WCH1-…</span>. That is more robust if an appliance is added later and the order shifts.",

"LOX.MEHRERE_GERAETE": "Several appliances — one virtual input per appliance:",
"LOX.S4_LEER": "<b>Not every provider supplies every value.</b> Home Connect reports neither energy nor water consumption; SmartThings reports no progress in percent; Miele supplies both, but only for appliances with EcoFeedback. What is missing is a dash &mdash; not a zero.",
"LOX.T_VA_START": "Start programme (the one selected on the appliance)",
"LOX.T_VA_START_PROG": "Start a specific programme",
"LOX.T_VA_STOP": "Abort programme",
"LOX.T_VA_PAUSE": "Pause programme",
"LOX.T_VA_FORTSETZEN": "Resume programme",
"LOX.T_VA_EIN": "Switch appliance on",
"LOX.T_VA_AUS": "Switch appliance off",

"TEST.F_ANBIETER": "Is at least one provider enabled?",
"TEST.A_ANBIETER": "yes, %d",
"TEST.A_KEIN_ANBIETER": "no — Settings tab",
"TEST.F_ZUGANG": "%s: are credentials stored?",
"TEST.A_ZUGANG_DA": "yes",
"TEST.A_ZUGANG_FEHLT": "no",
"TEST.F_ANGEMELDET": "%s: is sign-in complete?",
"TEST.A_ANGEMELDET": "yes, the service refreshes itself",
"TEST.A_NICHT_ANGEMELDET": "no — Settings tab, Sign-in section",
"TEST.A_ST_TOKEN": "not applicable — SmartThings only needs the token (valid 24 hours)",
"TEST.F_GERAETE": "Have appliances been detected?",
"TEST.A_GERAETE": "yes, %d",
"TEST.A_KEINE_GERAETE": "no — normal until the first successful poll",
"TEST.F_AUSFALL": "Did %s answer?",
"TEST.L_GERAET": "Appliance (running number)",
"TEST.L_PROGRAMM": "Programme (optional)",
"TEST.H_PROGRAMM": "Leave empty to start the programme selected on the appliance &mdash; that is the normal case. A Home Connect programme key looks like <span class='sm-mono'>LaundryCare.Washer.Program.Cotton</span>; the button <i>View raw data as JSON</i> shows which ones exist.",
"TEST.M_GERAET_UNGUELTIG": "The appliance number is not a number between 1 and 999.",
"TEST.M_PROGRAMM_UNGUELTIG": "The programme key contains characters that do not occur there. It was not sent.",
"TEST.K_STATUS": "Fetch status",
"TEST.K_VERBRAUCH": "Fetch consumption",
"TEST.K_GERAETE": "List appliances",
"TEST.K_START": "Start programme",
"TEST.K_STOP": "Abort programme",
"TEST.K_PAUSE": "Pause",
"TEST.K_FORTSETZEN": "Resume",
"TEST.K_EIN": "Appliance on",
"TEST.K_AUS": "Appliance off",

"WW_FELD.ZUSTAND": "0 off, 1 ready, 2 running, 3 paused, 4 finished, 5 fault",
"WW_FELD.LAEUFT": "1 = a programme is running",
"WW_FELD.FERTIG": "1 = programme finished, not yet acknowledged",
"WW_FELD.VERBUNDEN": "1 = the appliance is reachable for the provider",
"WW_FELD.TUER": "1 = door open",
"WW_FELD.FORTSCHR": "Progress of the running programme",
"WW_FELD.RESTMIN": "Time left until the programme ends",
"WW_FELD.STARTMIN": "Time until start when a delayed start is set",
"WW_FELD.LAUFMIN": "Elapsed time of the programme",
"WW_FELD.FERNSTART": "1 = remote start is released on the appliance",
"WW_FELD.FERNBED": "1 = remote control is allowed",
"WW_FELD.NETZ": "1 = appliance switched on",

"WW_VFELD.ENERGIE": "Energy used by the running programme",
"WW_VFELD.WASSER": "Water used by the running programme",
"WW_VFELD.TEMP": "Configured temperature",
"WW_VFELD.SCHLEUDER": "Configured spin speed",

"WW_MQTT.GERAETE": "Number of detected appliances",
"WW_MQTT.NAME": "Name of the appliance",
"WW_MQTT.ANBIETER": "homeconnect, miele or smartthings",
"WW_MQTT.ZUSTAND": "0 off, 1 ready, 2 running, 3 paused, 4 finished, 5 fault",
"WW_MQTT.ZUSTAND_TEXT": "State in plain text, as the provider names it",
"WW_MQTT.LAEUFT": "1 = a programme is running",
"WW_MQTT.FERTIG": "1 = programme finished",
"WW_MQTT.VERBUNDEN": "1 = reachable for the provider",
"WW_MQTT.TUER": "1 = door open",
"WW_MQTT.FORTSCHRITT": "Progress in percent",
"WW_MQTT.RESTZEIT": "Time left in minutes",
"WW_MQTT.STARTZEIT": "Time until start in minutes",
"WW_MQTT.LAUFZEIT": "Elapsed time in minutes",
"WW_MQTT.FERNSTART": "1 = remote start released on the appliance",
"WW_MQTT.FERNBED": "1 = remote control allowed",
"WW_MQTT.NETZ": "1 = appliance switched on",
"WW_MQTT.ENERGIE": "Energy used in kWh",
"WW_MQTT.WASSER": "Water used in litres",
"WW_MQTT.TEMPERATUR": "Configured temperature in degrees Celsius",
"WW_MQTT.SCHLEUDER": "Configured spin speed",
"WW_MQTT.PROGRAMM": "Running programme in plain text",
}
